config/routes.rb
Heraldo::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete 'users/sign_out', to: 'omniauth_callbacks#destroy'
    resources :users, only: [ :edit, :update ]
  end

  resources :tournaments do
    member do
      get :management
    end
  end

  resources :subscriptions, only: [ :create, :destroy ]
  resources :armies, only: [ :update ]
  resources :comments, only: [ :create ]

  get 'dashboard', to: 'dashboard#index'

  root 'tournaments#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @tournaments = current_user.tournaments
    @subscriptions = current_user.subscriptions
  end
end

app/views/dashboard/_tournaments_box.html.haml
.panel.panel-default
  .panel-heading
    %i.icon-flag.icon-large
    = t( 'heraldo.tournaments_box.panel_heading' )

    = link_to new_tournament_path, class: 'btn btn-xs btn-warning pull-right' do
      %i.icon-plus
      = t( 'actions.create' )

  %ul.list-group
    - tournaments.each do |tournament|
      = link_to tournament_path( tournament ) do
        %li.list-group-item
          %span.ellipsed
            = tournament.title
          %span.pull-right
            = "(#{tournament.subscriptions.count}/#{tournament.max_users})"


.panel.panel-default
  .panel-heading
    %i.icon-trophy.icon-large
    = t( 'heraldo.subscriptions_box.panel_heading' )

  %ul.list-group
    - subscriptions.each do |subscription|
      = link_to tournament_path( subscription.tournament ) do
        %li.list-group-item
          %span.ellipsed
            = subscription.tournament.title
          %span.pull-right
            = subscription_label( subscription.status )

app/views/dashboard/index.html.haml
.row
  .col-md-8
  .col-md-4
    - if current_user
      = render 'tournaments_box', tournaments: @tournaments, subscriptions: @subscriptions