config/routes.rb
Heraldo::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete 'users/sign_out', to: 'omniauth_callbacks#destroy'
    resources :users, only: [ :edit, :update ]
  end

  resources :tournaments do
    member do
      get :management
    end
  end

  resources :subscriptions, only: [ :create, :destroy ]
  resources :armies, only: [ :update ]
  resources :comments, only: [ :create ]

  get 'dashboard', to: 'dashboard#index'

  root 'tournaments#index'
end

app/models/tournament.rb
class Tournament
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  MINIMUM_PLAYERS = 4

  field :title,        type: String
  field :description,  type: String
  field :web,          type: String
  field :date,         type: DateTime
  field :sign_up_date, type: DateTime
  field :address,      type: String
  field :max_users,    type: Integer

  has_mongoid_attached_file :poster,
    styles: {
      original: ['1920x1680>', :jpg],
      small:    ['100x100#',   :jpg],
      medium:   ['250x250',    :jpg],
      large:    ['500x500>',   :jpg]
    },
    convert_options: {
      all: '-background white -flatten +matte'
    }

  field :remove_poster, type: String

  belongs_to :user
  has_many :subscriptions

  validates_presence_of :title
  validates_presence_of :date
  validates_presence_of :sign_up_date
  validates_presence_of :address
  validates_presence_of :max_users
  validates_presence_of :user

  validates_numericality_of :max_users,
    greater_than_or_equal_to: MINIMUM_PLAYERS,
    even: true
  validates_datetime :date,
    on_or_after: :today

  validates_datetime :sign_up_date,
    on_or_before: :date

  before_save do
    self.poster = nil if remove_poster == 'true'
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_filter :authenticate_user!, except: [ :index, :show ]

  load_and_authorize_resource

  def index
    respond_with @tournaments
  end

  def show
    respond_with @tournament
  end

  def management
    respond_with @tournament
  end

  def new
  end

  def create
    @tournament = Tournament.new( create_params )
    @tournament.user = current_user
    @tournament.save

    respond_with @tournament
  end

  def edit
  end

  def update
    @tournament.update_attributes( update_params )

    respond_with @tournament
  end

  def destroy
    @tournament.destroy

    respond_with @tournament
  end

  private

  def create_params
    params.require( :tournament ).permit( :title,:date,:sign_up_date,:address,:max_users,:user )
  end

  def update_params
    params.require( :tournament ).permit( :title,:date,:sign_up_date,:address,:max_users )
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def subscription_label( status )
    classes = { pending: 'warning', confirmed: 'info', banned: 'danger' }
    content_tag( :span, class: "label label-#{classes[status]}" ) do
      t( "mongoid.attributes.subscription.statuses.#{status}" ).capitalize
    end
  end
end

app/views/tournaments/_armies.html.haml
%h5
  %strong
    Army list
  %small.pull-right.top-padded
    = "#{t( 'mongoid.attributes.army.last_update' ).capitalize}:"
    = I18n.l subscription.army.updated_at, format: :short
= form_for subscription.army, html: { class: 'form-horizontal hide army-form', role: 'form' } do |form|
  .form-group
    = form.text_area :list, class: 'form-control', placeholder: t( 'mongoid.attributes.army.list' ).capitalize, rows: 10
  .form-group
    = form.button type: :submit, class: 'btn btn-sm btn-primary' do
      %i.icon-upload
      = t( 'actions.save' )
    = link_to '#', class: 'btn btn-sm btn-default army-cancel' do
      %i.icon-remove
      = t( 'actions.cancel' )

.army-list-container
  .army-list
    = markdown( subscription.army.list )
  = link_to '#', class: 'btn btn-sm btn-primary army-edit' do
    %i.icon-pencil
    = t( 'actions.edit' )

app/views/tournaments/_buttons.html.haml
.pull-right
  - if current_user.tournaments.include?( tournament )
    = link_to management_tournament_path( tournament ), class: 'btn btn-warning' do
      %i.icon-wrench
      = t( 'actions.manage' )
    = link_to edit_tournament_path( tournament ), class: 'btn btn-primary' do
      %i.icon-edit
      = t( 'actions.edit' )

  - if subscription = current_user.subscription_to( tournament )
    = link_to subscription_path( subscription ), method: :delete, class: 'btn btn-danger' do
      %i.icon-remove
      = t( 'actions.sign_out' )
  - else
    = form_tag subscriptions_path, class: 'inline', role: 'form' do
      = hidden_field_tag 'subscription[tournament_id]', tournament.id.to_s
      = button_tag type: 'submit', class: 'btn btn-success' do
        %i.icon-ok
        = t( 'actions.sign_up' )

app/views/tournaments/_comments.html.haml
%h5
  %strong
    Comments

- subscription.comments.each_with_index do |comment, index|
  .blockquote-box.clearfix.right-bordered
    .square.right-margined.pull-left
      = image_tag comment.user.avatar, class: 'img-rounded'

    = link_to comment.user.name, user_path( comment.user )
    %small.subtle
      = time_ago_in_words( comment.created_at )
    %p
      = comment.content

%hr
= form_for subscription.comments.new, html: { class: 'form-horizontal', role: 'form' } do |form|
  .form-group
    = form.text_area :content, class: 'form-control', placeholder: t( 'mongoid.attributes.comment.content' ).capitalize, rows: 3
  .form-group
    = form.button type: :submit, class: 'btn btn-sm btn-primary' do
      %i.icon-upload
      = t( 'actions.save' )

app/views/tournaments/_form.html.haml
.row
  .col-md-12
    = form_for @tournament, html: { class: 'form-horizontal', role: 'form' } do |form|
      = form.error_messages

      .row.bottom-margined
        .col-md-3
          %span#img-selector-img.img-selector-container
            %img.img-thumbnail{ src: form.object.poster.exists? ? form.object.poster.url : nil }
            %span.img-selector-remove-container.pull-right
              %i#img-selector-remove.icon-trash.icon-large
          %span#img-selector-empty.img-thumbnail.img-selector-container
            .img-selector-empty
              %i.icon-plus
              = t( 'actions.add_poster' )

          .form-group
            = form.file_field :poster, class: 'form-control', placeholder: t( 'mongoid.attributes.tournament.poster' ).capitalize
            = form.hidden_field :remove_poster, value: 'false'

        .col-md-4
          .form-group
            = form.text_field :title, class: 'form-control', placeholder: t( 'mongoid.attributes.tournament.title' ).capitalize

          .form-group
            = form.text_area :description, class: 'form-control', placeholder: t( 'mongoid.attributes.tournament.description' ).capitalize, rows: 5

          .form-group
            .input-group
              = form.text_field :sign_up_date, class: 'form-control datepicker', readonly: true, placeholder: t( 'mongoid.attributes.tournament.sign_up_date' ).capitalize
              .input-group-addon
                %i.icon-calendar

          .form-group
            .input-group
              = form.text_field :date, class: 'form-control datepicker', readonly: true, placeholder: t( 'mongoid.attributes.tournament.date' ).capitalize
              .input-group-addon
                %i.icon-calendar

          .form-group
            = form.text_field :address, class: 'form-control', placeholder: t( 'mongoid.attributes.tournament.address' ).capitalize

          .form-group
            = form.text_field :web, class: 'form-control', placeholder: t( 'mongoid.attributes.tournament.web' ).capitalize

          .form-group
            = form.text_field :max_users, class: 'form-control', type: 'number', min: 2, placeholder: t( 'mongoid.attributes.tournament.max_users' ).capitalize

        .col-md-5

      .row.bottom-margined
        .col-md-offset-2.col-md-10
          .form-group
            = link_to tournaments_path, class: 'btn btn-small btn-default' do
              %i.icon-cancel-white
              = t( 'actions.cancel' )

            = form.submit class: 'btn btn-small btn-primary'

app/views/tournaments/_panel_information.html.haml
.panel.panel-info
  .panel-heading
    %i.icon-map-marker
    = t( 'heraldo.tournament_info.panel_heading' )

  .panel-body
    %p
      %small
        %strong
          = "#{t( 'mongoid.attributes.tournament.user' ).capitalize}:"
        = tournament.user.name
    %p
      %small
        %strong
          = "#{t( 'mongoid.attributes.tournament.address' ).capitalize}:"
        = tournament.address
    %p
      %small
        %strong
          = "#{t( 'mongoid.attributes.tournament.sign_up_date' ).capitalize}:"
        = I18n.l tournament.sign_up_date
    %p
      %small
        %strong
          = "#{t( 'mongoid.attributes.tournament.date' ).capitalize}:"
        = I18n.l tournament.date
    %p
      %small
        %strong
          = "#{t( 'mongoid.attributes.tournament.max_users' ).capitalize}:"
        = tournament.max_users
    %p
      %small
        %strong
          = link_to t( 'mongoid.attributes.tournament.web' ).capitalize, external_link( tournament.web )

app/views/tournaments/_subscription.html.haml
%tr{ class: current_user.subscriptions.include?( subscription ) ? 'success' : '' }
  %td
    %strong
      = "##{subscription.identifier}"
  %td
    = image_tag subscription.user.avatar, class: 'img-rounded img-mini'
  %td
    = subscription.user.name
  %td
    = I18n.l subscription.created_at, format: :condensed
  %td
    %h4
      = subscription_label( subscription.status )

app/views/tournaments/edit.html.haml
= render 'form'

app/views/tournaments/index.html.haml
%table.table
  - @tournaments.each do |tournament|
    %tr
      %td
        = tournament.id
      %td
        = tournament.title
      %td
        = tournament.date
      %td
        = tournament.address

app/views/tournaments/management.html.haml
.row.bottom-margined
  .col-md-8
    %h2.tournament-header
      = @tournament.title
  .col-md-4
    .pull-right
      = link_to tournament_path( @tournament ), class: 'btn btn-default' do
        %i.icon-reply
        Back

.row
  .col-md-9
    #accordion.panel-group
      - @tournament.subscriptions.each do |subscription|
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{ 'data-toggle' => 'collapse', 'data-parent' => '#accordion', 'href' => "##{subscription.id.to_s}" }
                %strong
                  = "##{subscription.identifier}"
                = subscription.user.name
              %span.pull-right
                = subscription_label( subscription.status )

          .panel-collapse.collapse{ id: subscription.id.to_s }
            .panel-body
              .col-md-5.army-container
                = render 'armies', subscription: subscription
              .col-md-5
                = render 'comments', subscription: subscription
              .col-md-2
                .container
                  .btn-group-vertical
                    - if subscription.status != :pending
                      %button.btn.btn-warning.btn-sm
                        %i.icon-reply
                        Pending

                    - if subscription.status != :confirmed
                      %button.btn.btn-primary.btn-sm
                        %i.icon-ok
                        Confirm

                    - if subscription.status != :banned
                      %button.btn.btn-danger.btn-sm
                        %i.icon-remove
                        Ban

app/views/tournaments/new.html.haml
= render 'form'

app/views/tournaments/show.html.haml
.row.bottom-margined
  .col-md-8
    %h2.tournament-header
      %i.icon-trophy
      = @tournament.title
  .col-md-4
    = render 'buttons', tournament: @tournament

.row.bottom-margined
  .col-md-3
    = image_tag @tournament.poster.url, class: 'img-thumbnail'

  .col-md-6
    %p
      %small
        = markdown( @tournament.description )

  .col-md-3
    = render 'panel_information', tournament: @tournament

.row
  .col-md-6
    %h3
      = t( 'mongoid.models.subscription' ).pluralize.capitalize

    %table.table.table-condensed.table-striped.table-hover.vertical-aligned
      %tbody
        = render partial: 'subscription', collection: @tournament.subscriptions
  - if subscription = current_user.subscription_to( @tournament )
    .col-md-6.army-container
      %h4
        Your Army
        %small.pull-right.top-padded
          = "#{t( 'mongoid.attributes.army.last_update' ).capitalize}:"
          = I18n.l subscription.army.updated_at, format: :short
      = form_for subscription.army, html: { class: 'form-horizontal hide army-form', role: 'form' } do |form|
        .form-group
          = form.text_area :list, class: 'form-control', placeholder: t( 'mongoid.attributes.army.list' ).capitalize, rows: 10
        .form-group
          = form.button type: :submit, class: 'btn btn-small btn-primary' do
            %i.icon-upload
            = t( 'actions.save' )
          = link_to '#', class: 'btn btn-default army-cancel' do
            %i.icon-remove
            = t( 'actions.cancel' )
      .army-list-container
        .army-list
          = markdown( subscription.army.list )
        = link_to '#', class: 'btn btn-primary army-edit' do
          %i.icon-pencil
          = t( 'actions.edit' )