config/routes.rb
Heraldo::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete 'users/sign_out', to: 'omniauth_callbacks#destroy'
    resources :users, only: [ :edit, :update ]
  end

  resources :tournaments do
    member do
      get :management
    end
  end

  resources :subscriptions, only: [ :create, :destroy ]
  resources :armies, only: [ :update ]
  resources :comments, only: [ :create ]

  get 'dashboard', to: 'dashboard#index'

  root 'tournaments#index'
end

app/views/shared/_navbar.html.haml
.navbar.navbar-default{ role: 'navigation' }
  .container
    .navbar-header
      .navbar-brand
        = link_to dashboard_path do
          = t( 'heraldo.title' )

    .collapse.navbar-collapse
      %form.navbar-form.navbar-left.search-form
        .input-group
          %input.form-control{ type: 'text', placeholder: t( 'heraldo.search' ) }
          %span.input-group-btn
            %button.btn.btn-default{ type: 'submit' }
              = t( 'actions.search' )

      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{ 'data-toggle' => 'dropdown', 'href' => '#' }
              = current_user.name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to edit_user_path( current_user ) do
                  %i.icon-user
                  = t( 'actions.edit_profile' )
              %li.divider
              %li
                = link_to users_sign_out_path, method: :delete do
                  %i.icon-off
                  = t( 'actions.log_out' )
        - else
          %li.login-icon
            = link_to user_omniauth_authorize_path( :github ) do
              %i.icon-github-sign.icon-2x
          %li.login-icon
            = link_to user_omniauth_authorize_path( :google_oauth2 ) do
              %i.icon-google-plus-sign.icon-2x
          %li.login-icon
            = link_to user_omniauth_authorize_path( :twitter ) do
              %i.icon-twitter-sign.icon-2x